name: Hello World

on: 
  workflow_dispatch:
  push:
  
jobs:
    hello-job:
      strategy:
        matrix:
          os: [ubuntu-latest, ubuntu-20.04]
          image: [hello-world, alpine]
      runs-on: ${{ matrix.os }}
      steps:
      - name: Run docker on ${{matrix.os}} 
        run: docker run ${{matrix.image}}
        